version: '3.8'

services:
  learning-api:
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - la-redis:redis
      - la-postgres:postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=learning_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - JWT_SECRET=dev-secret-key-change-me-in-production
      - MATERIALS_BUCKET=learning-platform-materials
      - GCS_ENABLED=false
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - "8080:8080"
    networks:
      - la-network
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

networks:
  la-network:
    external: true
    name: la-network
